making sure its packaged right before its made

diff --git a/packages/openjdk-21/packaging b/packages/openjdk-21/packaging
--- a/packages/openjdk-21/packaging
+++ b/packages/openjdk-21/packaging
@@ -20,3 +20,13 @@ fi
 
 cd ${BOSH_INSTALL_TARGET}
 tar zxvf ${BOSH_COMPILE_TARGET}/*.tar.gz --strip 1
+if [ $? -ne 0 ]; then
+  echo "Error: Failed to extract tar.gz archive to bosh folder"
+  exit 1
+fi
+
+# Verify that at least one file was extracted to the bosh folder
+if [ ! -n "$(find ${BOSH_INSTALL_TARGET}/bosh -maxdepth 1 -type f)" ]; then
+    echo "Error: No files were extracted to the bosh folder."
+    exit 1
+fi
