fix to right version

diff --git a/packages/openjdk-21/packaging b/packages/openjdk-21/packaging
--- a/packages/openjdk-21/packaging
+++ b/packages/openjdk-21/packaging
@@ -4,8 +4,19 @@ export JAVA_HOME=/var/vcap/packages/openjdk-21
 export PATH=$JAVA_HOME/bin:$PATH
 
 mkdir ${BOSH_INSTALL_TARGET}/bosh
+
+# Copy runtime.env and compile.env to the bosh folder
 cp openjdk-21/runtime.env ${BOSH_INSTALL_TARGET}/bosh/runtime.env
+if [ $? -ne 0 ]; then
+  echo "Error: Failed to copy runtime.env"
+  exit 1
+fi
+
 cp openjdk-21/compile.env ${BOSH_INSTALL_TARGET}/bosh/compile.env
+if [ $? -ne 0 ]; then
+  echo "Error: Failed to copy compile.env"
+  exit 1
+fi
 
 cd ${BOSH_INSTALL_TARGET}
-# tar zxvf ${BOSH_COMPILE_TARGET}/*.tar.gz --strip 1
+tar zxvf ${BOSH_COMPILE_TARGET}/*.tar.gz --strip 1
